### ISSUE TITLE
Design database table structure

### ISSUE THREAD

**Issue by krlight** [krlight/inside#6]
* Design
* Explain it, write some instructions

Please email/slack me your progress asap, I am happy to discuss this with you.

**Comment by Vetteru** [comment]
<h1>API (plan)</h1>
<ul>
<li>GET /api/users/photo/:_id</li>
    - get profile photo
<li>GET /api/users/introduction/:_id</li>
    - get introduction
<li>GET /api/users/current/:_id</li>
    - get current state
<li>GET /api/users/papers/:_id</li>
    - get paper list
</ul>

**Comment by krlight** [comment]
Good job!

**Comment by krlight** [comment]
Good job! Please write these down to `DEVELOP.md`

**Comment by krlight** [comment]
Please work on `dev`
